package com.aldeiaconsultoriajr.conversor;

import com.constanzooficial.integracao.controller.nfse.sp.saoPaulo.ooralgua.ControllerLeitor;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Yuri Fernandes de Oliveira
 */
public class telaEmpresaEspecifica extends javax.swing.JFrame {

    /**
     * Creates new form ViewDemo
     */
    public telaEmpresaEspecifica() {
        initComponents();
        this.setLocationRelativeTo(null);

        try {
            Image iconePrograma = ImageIO.read(getClass().getResourceAsStream("/res/iconeNFSe.png"));
            this.setIconImage(iconePrograma);

            BufferedImage iconeAbrirArquivo = ImageIO.read(getClass().getResourceAsStream("/res/iconeAbrirArquivo.png"));
            Image dimg = iconeAbrirArquivo.getScaledInstance(btnSelecaoArquivo.getWidth() - 15, btnSelecaoArquivo.getHeight() - 10, Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(dimg);
            btnSelecaoArquivo.setIcon(imageIcon);

        } catch (IOException ex) {
            Logger.getLogger(telaEmpresaEspecifica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnConverterArquivo = new javax.swing.JButton();
        comboEmpresa = new javax.swing.JComboBox<>();
        campoCaminhoArquivo = new javax.swing.JTextField();
        btnSelecaoArquivo = new javax.swing.JButton();
        radioEmitidas = new javax.swing.JRadioButton();
        radioRecebidas = new javax.swing.JRadioButton();
        btnConsiderarISS = new javax.swing.JCheckBox();
        comboMes = new javax.swing.JComboBox<>();
        labelPrimeiro = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        campoPrimeiroNumero = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuConversor = new javax.swing.JMenu();
        menuNfseMunicipais = new javax.swing.JMenuItem();
        menuEmpresasEspecificas = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de NFSe Municipal");
        setMinimumSize(new java.awt.Dimension(500, 200));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(null);

        btnConverterArquivo.setText("Converter Arquivo");
        btnConverterArquivo.setEnabled(false);
        btnConverterArquivo.setMargin(new java.awt.Insets(50, 50, 50, 50));
        btnConverterArquivo.setMaximumSize(new java.awt.Dimension(120, 40));
        btnConverterArquivo.setMinimumSize(new java.awt.Dimension(120, 40));
        btnConverterArquivo.setPreferredSize(new java.awt.Dimension(120, 40));
        btnConverterArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConverterArquivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnConverterArquivo);
        btnConverterArquivo.setBounds(160, 90, 300, 30);

        comboEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empresa", "OORALGUA" }));
        comboEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEmpresaActionPerformed(evt);
            }
        });
        jPanel1.add(comboEmpresa);
        comboEmpresa.setBounds(10, 10, 140, 30);

        campoCaminhoArquivo.setEditable(false);
        campoCaminhoArquivo.setText("Selecione uma empresa");
        campoCaminhoArquivo.setFocusable(false);
        jPanel1.add(campoCaminhoArquivo);
        campoCaminhoArquivo.setBounds(160, 10, 270, 30);

        btnSelecaoArquivo.setToolTipText("");
        btnSelecaoArquivo.setBorderPainted(false);
        btnSelecaoArquivo.setEnabled(false);
        btnSelecaoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecaoArquivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelecaoArquivo);
        btnSelecaoArquivo.setBounds(420, 10, 40, 30);

        btnGroupTipo.add(radioEmitidas);
        radioEmitidas.setText("NFSe Emitidas");
        radioEmitidas.setEnabled(false);
        radioEmitidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEmitidasActionPerformed(evt);
            }
        });
        jPanel1.add(radioEmitidas);
        radioEmitidas.setBounds(10, 50, 120, 23);

        btnGroupTipo.add(radioRecebidas);
        radioRecebidas.setText("NFSe Recebidas");
        radioRecebidas.setEnabled(false);
        radioRecebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRecebidasActionPerformed(evt);
            }
        });
        jPanel1.add(radioRecebidas);
        radioRecebidas.setBounds(10, 70, 120, 23);

        btnConsiderarISS.setText("Considerar ISS");
        btnConsiderarISS.setEnabled(false);
        btnConsiderarISS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsiderarISSActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsiderarISS);
        btnConsiderarISS.setBounds(10, 90, 130, 23);

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        comboMes.setEnabled(false);
        comboMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMesActionPerformed(evt);
            }
        });
        jPanel1.add(comboMes);
        comboMes.setBounds(160, 50, 140, 30);

        labelPrimeiro.setText("Primeiro");
        labelPrimeiro.setEnabled(false);
        jPanel1.add(labelPrimeiro);
        labelPrimeiro.setBounds(330, 50, 60, 14);

        labelNumero.setText("número:");
        labelNumero.setEnabled(false);
        jPanel1.add(labelNumero);
        labelNumero.setBounds(330, 70, 60, 14);

        campoPrimeiroNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        campoPrimeiroNumero.setEnabled(false);
        campoPrimeiroNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPrimeiroNumeroKeyReleased(evt);
            }
        });
        jPanel1.add(campoPrimeiroNumero);
        campoPrimeiroNumero.setBounds(380, 50, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 470, 130);

        menuConversor.setText("Conversor");

        menuNfseMunicipais.setText("NFSe Municipais");
        menuNfseMunicipais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNfseMunicipaisActionPerformed(evt);
            }
        });
        menuConversor.add(menuNfseMunicipais);

        menuEmpresasEspecificas.setText("Empresas Específicas");
        menuEmpresasEspecificas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpresasEspecificasActionPerformed(evt);
            }
        });
        menuConversor.add(menuEmpresasEspecificas);

        jMenuBar1.add(menuConversor);

        menuSobre.setText("Sobre");
        menuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSobre);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConverterArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConverterArquivoActionPerformed

        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        File arquivo = new File(campoCaminhoArquivo.getText());

        switch (comboEmpresa.getSelectedItem().toString()) {

            case "OORALGUA":
                /*
                ArrayList<com.constanzooficial.integracao.model.nfse.sp.saoPaulo.ooralgua.ModelRegistro> registros = null;
                try {
                    registros = new ControllerLeitor().lerArquivo(arquivo, comboMes.getSelectedIndex());
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }

                if (registros != null) {
                    try {
                        com.constanzooficial.integracao.model.nfse.sp.saoPaulo.ooralgua.GeradorTXT geradorTxt = new com.constanzooficial.integracao.model.nfse.sp.saoPaulo.ooralgua.GeradorTXT(registros);
                        String caminhoArquivo = arquivo.getAbsolutePath().replaceAll(arquivo.getName(), "");
                        geradorTxt.gerarTXT(caminhoArquivo, Integer.parseInt(campoPrimeiroNumero.getText()), false);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }
                }
                */
                break;
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        JOptionPane.showMessageDialog(null, "Conversão concluída com sucesso!");
    }//GEN-LAST:event_btnConverterArquivoActionPerformed

    private void comboEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEmpresaActionPerformed
        switch (comboEmpresa.getSelectedItem().toString()) {
            case "Empresa":
                campoCaminhoArquivo.setText("Selecione uma empresa");
                btnSelecaoArquivo.setEnabled(false);
                radioEmitidas.setEnabled(false);
                radioRecebidas.setEnabled(false);
                btnConsiderarISS.setSelected(false);
                btnConsiderarISS.setEnabled(false);
                comboMes.setSelectedIndex(0);
                comboMes.setEnabled(false);
                labelPrimeiro.setEnabled(false);
                labelNumero.setEnabled(false);
                campoPrimeiroNumero.setText("");
                campoPrimeiroNumero.setEnabled(false);
                break;
            case "OORALGUA":
                campoCaminhoArquivo.setText("Selecione o arquivo do Excel");
                btnSelecaoArquivo.setEnabled(true);
                break;
            default:
                campoCaminhoArquivo.setText("");
                btnSelecaoArquivo.setEnabled(true);
                break;
        }
        btnGroupTipo.clearSelection();
        radioEmitidas.setEnabled(false);
        radioRecebidas.setEnabled(false);
        btnConsiderarISS.setEnabled(false);
        btnConverterArquivo.setEnabled(false);
    }//GEN-LAST:event_comboEmpresaActionPerformed

    private void btnSelecaoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecaoArquivoActionPerformed

        JFileChooser fc = new JFileChooser(".");
        switch (comboEmpresa.getSelectedItem().toString()) {
            case "OORALGUA":
                fc.setFileFilter(new FileNameExtensionFilter("Excel", "xlsx"));
                break;
            default:
                fc.setFileFilter(new FileNameExtensionFilter("Excel", "xlsx"));
                break;
        }
        fc.setAcceptAllFileFilterUsed(false);
        int opcao = fc.showOpenDialog(null);
        if (opcao == JFileChooser.APPROVE_OPTION) {
            campoCaminhoArquivo.setText(fc.getSelectedFile().getPath());

            btnGroupTipo.clearSelection();

            switch (comboEmpresa.getSelectedItem().toString()) {
                case "OORALGUA":
                    radioEmitidas.setEnabled(true);
                    radioRecebidas.setEnabled(false);
                    radioEmitidas.doClick();
                    btnConsiderarISS.setSelected(false);
                    btnConsiderarISS.setEnabled(false);
                    break;
                default:
                    radioEmitidas.setEnabled(false);
                    radioRecebidas.setEnabled(false);
                    btnConsiderarISS.setSelected(false);
                    btnConsiderarISS.setEnabled(false);
                    comboMes.setSelectedIndex(0);
                    comboMes.setEnabled(false);
                    labelPrimeiro.setEnabled(false);
                    labelNumero.setEnabled(false);
                    campoPrimeiroNumero.setText("");
                    campoPrimeiroNumero.setEnabled(false);
                    break;
            }
        }
    }//GEN-LAST:event_btnSelecaoArquivoActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked

    private void radioEmitidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEmitidasActionPerformed
        comboMes.setEnabled(true);
        labelPrimeiro.setEnabled(true);
        labelNumero.setEnabled(true);
        campoPrimeiroNumero.setEnabled(true);
    }//GEN-LAST:event_radioEmitidasActionPerformed

    private void radioRecebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRecebidasActionPerformed
        comboMes.setEnabled(true);
        labelPrimeiro.setEnabled(true);
        labelNumero.setEnabled(true);
        campoPrimeiroNumero.setEnabled(true);
    }//GEN-LAST:event_radioRecebidasActionPerformed

    private void menuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSobreMouseClicked
        JOptionPane.showMessageDialog(null, "Conversor de NFSe de diversos municípios para o padrão aceito pelo Contmatic G5 Phoenix.\nDesenvolvido por Yuri Fernandes de Oliveira");
    }//GEN-LAST:event_menuSobreMouseClicked

    private void btnConsiderarISSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsiderarISSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsiderarISSActionPerformed

    private void menuNfseMunicipaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNfseMunicipaisActionPerformed
        new telaPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuNfseMunicipaisActionPerformed

    private void menuEmpresasEspecificasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpresasEspecificasActionPerformed
        new telaEmpresaEspecifica().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuEmpresasEspecificasActionPerformed

    private void comboMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMesActionPerformed
        if (!"".equals(campoPrimeiroNumero.getText())) {
            if (comboMes.getSelectedIndex() != 0) {
                btnConverterArquivo.setEnabled(true);
            } else {
                btnConverterArquivo.setEnabled(false);
            }
        } else {
            btnConverterArquivo.setEnabled(false);
        }
    }//GEN-LAST:event_comboMesActionPerformed

    private void campoPrimeiroNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPrimeiroNumeroKeyReleased
        if (comboMes.getSelectedIndex() != 0) {
            if (!"".equals(campoPrimeiroNumero.getText())) {
                btnConverterArquivo.setEnabled(true);
            } else {
                btnConverterArquivo.setEnabled(false);
            }
        } else {
            btnConverterArquivo.setEnabled(false);
        }
    }//GEN-LAST:event_campoPrimeiroNumeroKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.setLookAndFeel(new com.jgoodies.looks.plastic.Plastic3DLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new telaEmpresaEspecifica().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnConsiderarISS;
    private javax.swing.JButton btnConverterArquivo;
    private javax.swing.ButtonGroup btnGroupTipo;
    private javax.swing.JButton btnSelecaoArquivo;
    private javax.swing.JTextField campoCaminhoArquivo;
    private javax.swing.JFormattedTextField campoPrimeiroNumero;
    private javax.swing.JComboBox<String> comboEmpresa;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelPrimeiro;
    private javax.swing.JMenu menuConversor;
    private javax.swing.JMenuItem menuEmpresasEspecificas;
    private javax.swing.JMenuItem menuNfseMunicipais;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JRadioButton radioEmitidas;
    private javax.swing.JRadioButton radioRecebidas;
    // End of variables declaration//GEN-END:variables
}
