package com.constanzooficial.integracao.view;

import com.constanzooficial.integracao.controller.nfse.sp.saoPaulo.ooralgua.ControllerLeitor;
import com.constanzooficial.integracao.controller.nfse.sp.saoPaulo.v001.GeradorTXT;
import com.constanzooficial.integracao.model.nfse.sp.saoPaulo.v001.ModelNota;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Yuri Fernandes de Oliveira
 */
public class ViewEmpresaEspecifica extends javax.swing.JFrame {

    /**
     * Creates new form ViewDemo
     */
    public ViewEmpresaEspecifica() {
        initComponents();
        this.setLocationRelativeTo(null);

        try {
            Image iconePrograma = ImageIO.read(getClass().getResourceAsStream("/res/iconeNFSe.png"));
            this.setIconImage(iconePrograma);

            BufferedImage iconeAbrirArquivo = ImageIO.read(getClass().getResourceAsStream("/res/iconeAbrirArquivo.png"));
            Image dimg = iconeAbrirArquivo.getScaledInstance(btnSelecaoArquivo.getWidth() - 15, btnSelecaoArquivo.getHeight() - 10, Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(dimg);
            btnSelecaoArquivo.setIcon(imageIcon);

        } catch (IOException ex) {
            Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnConverterArquivo = new javax.swing.JButton();
        comboModelo = new javax.swing.JComboBox<>();
        campoCaminhoArquivo = new javax.swing.JTextField();
        btnSelecaoArquivo = new javax.swing.JButton();
        radioEmitidas = new javax.swing.JRadioButton();
        radioRecebidas = new javax.swing.JRadioButton();
        btnConsiderarISS = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conversor de NFSe de empresa específica");
        setMinimumSize(new java.awt.Dimension(500, 180));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(null);

        btnConverterArquivo.setText("Converter Arquivo");
        btnConverterArquivo.setEnabled(false);
        btnConverterArquivo.setMargin(new java.awt.Insets(50, 50, 50, 50));
        btnConverterArquivo.setMaximumSize(new java.awt.Dimension(120, 40));
        btnConverterArquivo.setMinimumSize(new java.awt.Dimension(120, 40));
        btnConverterArquivo.setPreferredSize(new java.awt.Dimension(120, 40));
        btnConverterArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConverterArquivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnConverterArquivo);
        btnConverterArquivo.setBounds(160, 80, 270, 30);

        comboModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modelo", "Excel Simples" }));
        comboModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboModeloActionPerformed(evt);
            }
        });
        jPanel1.add(comboModelo);
        comboModelo.setBounds(10, 10, 140, 30);

        campoCaminhoArquivo.setEditable(false);
        campoCaminhoArquivo.setText("Selecione um modelo");
        campoCaminhoArquivo.setFocusable(false);
        jPanel1.add(campoCaminhoArquivo);
        campoCaminhoArquivo.setBounds(160, 10, 270, 30);

        btnSelecaoArquivo.setToolTipText("");
        btnSelecaoArquivo.setBorderPainted(false);
        btnSelecaoArquivo.setEnabled(false);
        btnSelecaoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecaoArquivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelecaoArquivo);
        btnSelecaoArquivo.setBounds(420, 10, 40, 30);

        btnGroupTipo.add(radioEmitidas);
        radioEmitidas.setText("NFSe Emitidas");
        radioEmitidas.setEnabled(false);
        radioEmitidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEmitidasActionPerformed(evt);
            }
        });
        jPanel1.add(radioEmitidas);
        radioEmitidas.setBounds(10, 50, 120, 23);

        btnGroupTipo.add(radioRecebidas);
        radioRecebidas.setText("NFSe Recebidas");
        radioRecebidas.setEnabled(false);
        radioRecebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRecebidasActionPerformed(evt);
            }
        });
        jPanel1.add(radioRecebidas);
        radioRecebidas.setBounds(10, 70, 120, 23);

        btnConsiderarISS.setText("Considerar ISS");
        btnConsiderarISS.setEnabled(false);
        btnConsiderarISS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsiderarISSActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsiderarISS);
        btnConsiderarISS.setBounds(10, 90, 130, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 470, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConverterArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConverterArquivoActionPerformed

        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        File arquivo = new File(campoCaminhoArquivo.getText());

        switch (comboModelo.getSelectedItem().toString()) {

            case "Excel Simples":

                ModelNota nota = null;
                try {
                    nota = new ControllerLeitor().lerArquivo(arquivo);
                } catch (IOException ex) {
                    Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                }

                if (nota != null) {

                    try {
                        new GeradorTXT(nota).gerarTxt(arquivo.getAbsolutePath().replaceAll(arquivo.getName(), ""), GeradorTXT.EMITIDA);
                    } catch (IOException ex) {
                        Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(this, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                    }
                }
                break;
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        JOptionPane.showMessageDialog(null, "Conversão concluída com sucesso!");
    }//GEN-LAST:event_btnConverterArquivoActionPerformed

    private void comboModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboModeloActionPerformed
        switch (comboModelo.getSelectedItem().toString()) {
            case "Modelo":
                campoCaminhoArquivo.setText("Selecione um modelo");
                btnSelecaoArquivo.setEnabled(false);
                radioEmitidas.setEnabled(false);
                radioRecebidas.setEnabled(false);
                btnConsiderarISS.setSelected(false);
                btnConsiderarISS.setEnabled(false);
                break;
            case "Excel Simples":
                campoCaminhoArquivo.setText("Selecione o arquivo do Excel");
                btnSelecaoArquivo.setEnabled(true);
                break;
            default:
                campoCaminhoArquivo.setText("");
                btnSelecaoArquivo.setEnabled(true);
                break;
        }
        btnGroupTipo.clearSelection();
        radioEmitidas.setEnabled(false);
        radioRecebidas.setEnabled(false);
        btnConsiderarISS.setEnabled(false);
        btnConverterArquivo.setEnabled(false);
    }//GEN-LAST:event_comboModeloActionPerformed

    private void btnSelecaoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecaoArquivoActionPerformed

        JFileChooser fc = new JFileChooser(".");
        switch (comboModelo.getSelectedItem().toString()) {
            case "Excel Simples":
                fc.setFileFilter(new FileNameExtensionFilter("Excel", "xlsx"));
                break;
            default:
                fc.setFileFilter(new FileNameExtensionFilter("Excel", "xlsx"));
                break;
        }
        fc.setAcceptAllFileFilterUsed(false);
        int opcao = fc.showOpenDialog(null);
        if (opcao == JFileChooser.APPROVE_OPTION) {
            campoCaminhoArquivo.setText(fc.getSelectedFile().getPath());

            btnGroupTipo.clearSelection();

            switch (comboModelo.getSelectedItem().toString()) {
                case "Excel Simples":
                    radioEmitidas.setEnabled(true);
                    radioRecebidas.setEnabled(false);
                    radioEmitidas.doClick();
                    btnConsiderarISS.setSelected(false);
                    btnConsiderarISS.setEnabled(false);
                    break;
                default:
                    radioEmitidas.setEnabled(false);
                    radioRecebidas.setEnabled(false);
                    btnConsiderarISS.setSelected(false);
                    btnConsiderarISS.setEnabled(false);
                    break;
            }
        }
    }//GEN-LAST:event_btnSelecaoArquivoActionPerformed

    private void radioEmitidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEmitidasActionPerformed
        btnConverterArquivo.setEnabled(true);
    }//GEN-LAST:event_radioEmitidasActionPerformed

    private void radioRecebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRecebidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRecebidasActionPerformed

    private void btnConsiderarISSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsiderarISSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsiderarISSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.setLookAndFeel(new com.jgoodies.looks.plastic.Plastic3DLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
        } //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewEmpresaEspecifica().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnConsiderarISS;
    private javax.swing.JButton btnConverterArquivo;
    private javax.swing.ButtonGroup btnGroupTipo;
    private javax.swing.JButton btnSelecaoArquivo;
    private javax.swing.JTextField campoCaminhoArquivo;
    private javax.swing.JComboBox<String> comboModelo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioEmitidas;
    private javax.swing.JRadioButton radioRecebidas;
    // End of variables declaration//GEN-END:variables
}
