package com.constanzooficial.integracao.view;

import com.constanzooficial.integracao.controller.nfse.sp.saoPaulo.v001.GeradorTXT;
import com.constanzooficial.integracao.model.nfse.sp.saoPaulo.v001.ModelNota;
import com.constanzooficial.integracao.util.UtilZip;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author Yuri Fernandes de Oliveira
 */
public class ViewNotaMunicipal extends javax.swing.JFrame {

    private String path;
    private File[] selectedFiles;

    /**
     * Creates new form ViewDemo
     */
    public ViewNotaMunicipal() {
        initComponents();
        this.setLocationRelativeTo(null);

        try {
            Image iconePrograma = ImageIO.read(getClass().getResourceAsStream("/res/iconeNFSe.png"));
            this.setIconImage(iconePrograma);

            BufferedImage iconeAbrirArquivo = ImageIO.read(getClass().getResourceAsStream("/res/iconeAbrirArquivo.png"));
            Image dimg = iconeAbrirArquivo.getScaledInstance(btnSelecaoArquivo.getWidth() - 15, btnSelecaoArquivo.getHeight() - 10, Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(dimg);
            btnSelecaoArquivo.setIcon(imageIcon);

        } catch (IOException ex) {
            Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnConverterArquivo = new javax.swing.JButton();
        comboMunicipio = new javax.swing.JComboBox<>();
        campoCaminhoArquivo = new javax.swing.JTextField();
        btnSelecaoArquivo = new javax.swing.JButton();
        radioEmitidas = new javax.swing.JRadioButton();
        radioRecebidas = new javax.swing.JRadioButton();
        btnConsiderarISS = new javax.swing.JCheckBox();
        jProgressBar1 = new javax.swing.JProgressBar();
        comboPrestador = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conversor de NFSe Municipal");
        setMinimumSize(new java.awt.Dimension(500, 180));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        btnConverterArquivo.setText("Converter Arquivo");
        btnConverterArquivo.setEnabled(false);
        btnConverterArquivo.setMargin(new java.awt.Insets(50, 50, 50, 50));
        btnConverterArquivo.setMaximumSize(new java.awt.Dimension(120, 40));
        btnConverterArquivo.setMinimumSize(new java.awt.Dimension(120, 40));
        btnConverterArquivo.setPreferredSize(new java.awt.Dimension(120, 40));
        btnConverterArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConverterArquivoActionPerformed(evt);
            }
        });

        comboMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Município", "Agrolândia - SC", "Barueri - SP", "Bauru - SP", "Bento Gonçalves - RS", "Brasília - DF", "Campo Novo do Parecis - MT", "Canoas - RS", "Colatina - ES", "Cubatão - SP", "Goiânia - GO", "Ibaiti - PR", "Irecê - BA", "João Dourado - BA", "Mossoró - RN", "Nova Iguaçu - RJ", "Osasco - SP", "Rio Verde - GO", "Salvador - BA", "São Raimundo Nonato - PI", "São Vicente - SP", "Vila Velha - ES", "Vitória da Conquista - BA" }));
        comboMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMunicipioActionPerformed(evt);
            }
        });

        campoCaminhoArquivo.setEditable(false);
        campoCaminhoArquivo.setText("Selecione um município");
        campoCaminhoArquivo.setToolTipText("");
        campoCaminhoArquivo.setFocusable(false);
        campoCaminhoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCaminhoArquivoActionPerformed(evt);
            }
        });

        btnSelecaoArquivo.setToolTipText("");
        btnSelecaoArquivo.setEnabled(false);
        btnSelecaoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecaoArquivoActionPerformed(evt);
            }
        });

        btnGroupTipo.add(radioEmitidas);
        radioEmitidas.setText("NFSe Emitidas");
        radioEmitidas.setEnabled(false);
        radioEmitidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEmitidasActionPerformed(evt);
            }
        });

        btnGroupTipo.add(radioRecebidas);
        radioRecebidas.setText("NFSe Recebidas");
        radioRecebidas.setEnabled(false);
        radioRecebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRecebidasActionPerformed(evt);
            }
        });

        btnConsiderarISS.setText("Considerar ISS");
        btnConsiderarISS.setEnabled(false);
        btnConsiderarISS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsiderarISSActionPerformed(evt);
            }
        });

        jProgressBar1.setForeground(new java.awt.Color(0, 255, 0));

        comboPrestador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prestador", "Alpha Soluções", "Felipe Bernardes", "LB & Filhos", "Mendonça e Associados", "ZN Odontologia (Filial)", "ZN Odontologia (Matriz)" }));
        comboPrestador.setEnabled(false);
        comboPrestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPrestadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(campoCaminhoArquivo)
                        .addGap(0, 0, 0)
                        .addComponent(btnSelecaoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConverterArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radioEmitidas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioRecebidas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsiderarISS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCaminhoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecaoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioEmitidas)
                    .addComponent(radioRecebidas)
                    .addComponent(btnConsiderarISS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConverterArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConverterArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConverterArquivoActionPerformed

        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        path = campoCaminhoArquivo.getText();
        File f = new File(path);
        String destino = f.getAbsolutePath().replaceAll(f.getName(), "");

        GeradorTXT geradorTxt = null;

        switch (comboMunicipio.getSelectedItem().toString()) {

            case "Agrolândia - SC":
                try {
                    File destFolder = new File("tmp");
                    UtilZip.unzipArchive(new File(path), destFolder);

                    try {
                        com.aldeiaconsultoriajr.nfe.sc.agrolandia.LeitorXML leitorXML = new com.aldeiaconsultoriajr.nfe.sc.agrolandia.LeitorXML();
                        ArrayList<com.aldeiaconsultoriajr.nfe.sc.agrolandia.Nfse> listaNfse = leitorXML.lerXMLs(destFolder);
                        com.aldeiaconsultoriajr.nfe.sc.agrolandia.GeradorTXT geradorTXT = new com.aldeiaconsultoriajr.nfe.sc.agrolandia.GeradorTXT(listaNfse);
                        geradorTXT.gerarTXT(destino, btnConsiderarISS.isSelected());
                    } catch (Exception e) {
                        com.constanzooficial.integracao.controller.nfse.sc.agrolandia2.ControllerLeitor leitorXML = new com.constanzooficial.integracao.controller.nfse.sc.agrolandia2.ControllerLeitor();

                        try {
                            geradorTxt = new GeradorTXT(leitorXML.lerNotas(new File(destFolder.getAbsolutePath()), btnConsiderarISS.isSelected()));
                            geradorTxt.gerarTxt(selectedFiles[0].getParentFile().getPath(), radioEmitidas.isSelected() ? 0 : 1);
                        } catch (Exception ex) {
                            Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    FileUtils.deleteDirectory(destFolder);

                } catch (IOException ex) {
                    Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                break;

            case "Barueri - SP": {
                com.constanzooficial.integracao.controller.nfse.sp.barueri.ControllerLeitorTxt leitorBarueri = new com.constanzooficial.integracao.controller.nfse.sp.barueri.ControllerLeitorTxt();

                String cpfCnpjPrestador = null;
                switch (comboPrestador.getSelectedItem().toString()) {

                    case "Alpha Soluções":
                        cpfCnpjPrestador = "20494682000143";
                        break;
                    case "Felipe Bernardes":
                        cpfCnpjPrestador = "28078005000156";
                        break;
                    case "Mendonça e Associados":
                        cpfCnpjPrestador = "08924815000179";
                        break;
                }
                try {
                    geradorTxt = new GeradorTXT(leitorBarueri.lerNotas(selectedFiles, btnConsiderarISS.isSelected(), cpfCnpjPrestador));
                    geradorTxt.gerarTxt(selectedFiles[0].getParentFile().getPath(), radioEmitidas.isSelected() ? 0 : 1);
                } catch (IOException ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                }
                break;
            }
            
            case "Bauru - SP": {
                com.constanzooficial.integracao.controller.nfse.sp.bauru.ControllerLeitor leitorBauru = new com.constanzooficial.integracao.controller.nfse.sp.bauru.ControllerLeitor();

                try {
                    try {
                        geradorTxt = new GeradorTXT(leitorBauru.lerNotas(selectedFiles, btnConsiderarISS.isSelected()));
                    } catch (Exception ex) {
                        Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    geradorTxt.gerarTxt(selectedFiles[0].getParentFile().getPath(), radioEmitidas.isSelected() ? 0 : 1);
                } catch (IOException ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                }
                break;
            }

            case "Bento Gonçalves - RS": {
                try {
                    File destFolder = new File("tmp");
                    UtilZip.unzipArchive(new File(path), destFolder);

                    try {
                        com.constanzooficial.integracao.controller.nfse.rs.bentoGoncalves.ControllerLeitor leitorBentoGoncalves = new com.constanzooficial.integracao.controller.nfse.rs.bentoGoncalves.ControllerLeitor();
                        geradorTxt = new GeradorTXT(leitorBentoGoncalves.lerNotas(path, btnConsiderarISS.isSelected()));
                        geradorTxt.gerarTxt(selectedFiles[0].getParentFile().getPath(), radioEmitidas.isSelected() ? 0 : 1);
                    } catch (Exception ex) {
                        com.constanzooficial.integracao.controller.nfse.rs.bentoGoncalves2.ControllerLeitor leitorXML = new com.constanzooficial.integracao.controller.nfse.rs.bentoGoncalves2.ControllerLeitor();
                        ModelNota listaNfse;

                        try {
                            listaNfse = leitorXML.lerNotas(new File(destFolder.getAbsolutePath()), btnConsiderarISS.isSelected());
                            geradorTxt = new GeradorTXT(leitorXML.lerNotas(new File(destFolder.getAbsolutePath()), btnConsiderarISS.isSelected()));
                            geradorTxt.gerarTxt(selectedFiles[0].getParentFile().getPath(), radioEmitidas.isSelected() ? 0 : 1);
                        } catch (Exception e) {
                            Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, e);
                        }
                    }
                    FileUtils.deleteDirectory(destFolder);
                } catch (Exception ex) {
                    Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                break;
            }

            case "Brasília - DF": {
                com.constanzooficial.integracao.controller.nfse.df.brasilia.ControllerLeitor leitor = new com.constanzooficial.integracao.controller.nfse.df.brasilia.ControllerLeitor();

                try {
                    geradorTxt = new GeradorTXT(leitor.lerNotas(selectedFiles, btnConsiderarISS.isSelected()));
                    geradorTxt.gerarTxt(selectedFiles[0].getParentFile().getPath(), radioEmitidas.isSelected() ? 0 : 1);
                } catch (IOException ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                } catch (Exception ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            }
            
            case "Campo Novo do Parecis - MT": {
                com.constanzooficial.integracao.controller.nfse.mt.campoNovoDoParecis.ControllerLeitor leitorCampoNovoDoParecis = new com.constanzooficial.integracao.controller.nfse.mt.campoNovoDoParecis.ControllerLeitor();

                try {
                    geradorTxt = new GeradorTXT(leitorCampoNovoDoParecis.lerNotas(path, btnConsiderarISS.isSelected()));
                    geradorTxt.gerarTxt(selectedFiles[0].getParentFile().getPath(), radioEmitidas.isSelected() ? 0 : 1);
                } catch (Exception ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                }
                break;
            }

            case "Canoas - RS": {
                File destFolder = new File("tmp");
                
                try {
                    UtilZip.unzipArchive(new File(path), destFolder);
                    
                    com.aldeiaconsultoriajr.nfe.rs.canoas.LeitorXML leitorXML = new com.aldeiaconsultoriajr.nfe.rs.canoas.LeitorXML();
                    com.aldeiaconsultoriajr.nfe.rs.canoas.GeradorTXT geradorTXT = new com.aldeiaconsultoriajr.nfe.rs.canoas.GeradorTXT(leitorXML.lerXML(destFolder));
                    geradorTXT.gerarTXT(destino, btnConsiderarISS.isSelected());
                } catch (IOException ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                break;
            }

            case "Colatina - ES": {
                com.constanzooficial.integracao.controller.nfse.es.colatina.ControllerLeitor leitor = new com.constanzooficial.integracao.controller.nfse.es.colatina.ControllerLeitor();

                try {
                    geradorTxt = new GeradorTXT(leitor.lerNotas(path, btnConsiderarISS.isSelected()));
                    geradorTxt.gerarTxt(selectedFiles[0].getParent(), 0/*radioEmitidas.isSelected() ? 0 : 1*/);
                } catch (IOException ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                }
                break;
            }

            case "Cubatão - SP": {
                com.constanzooficial.integracao.controller.nfse.sp.cubatao.ControllerLeitor leitorCubatao = new com.constanzooficial.integracao.controller.nfse.sp.cubatao.ControllerLeitor();

                try {
                    try {
                        geradorTxt = new GeradorTXT(leitorCubatao.lerNotas(selectedFiles, btnConsiderarISS.isSelected()));
                    } catch (Exception ex) {
                        Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    geradorTxt.gerarTxt(selectedFiles[0].getParentFile().getPath(), radioEmitidas.isSelected() ? 0 : 1);
                } catch (IOException ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                }
                break;
            }
            
            case "Goiânia - GO": {
                com.constanzooficial.integracao.controller.nfse.go.goiania.ControllerLeitor leitorGoiania = new com.constanzooficial.integracao.controller.nfse.go.goiania.ControllerLeitor();

                try {
                    geradorTxt = new GeradorTXT(leitorGoiania.lerNotas(path, btnConsiderarISS.isSelected()));
                    geradorTxt.gerarTxt(selectedFiles[0].getParentFile().getPath(), radioEmitidas.isSelected() ? 0 : 1);
                } catch (Exception ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                }
                break;
            }

            case "Ibaiti - PR": {
                com.aldeiaconsultoriajr.nfe.pr.ibaiti.LeitorXML leitorXMLIbaiti = new com.aldeiaconsultoriajr.nfe.pr.ibaiti.LeitorXML();
                try {
                    com.aldeiaconsultoriajr.nfe.pr.ibaiti.GeradorTXT geradorTXT = new com.aldeiaconsultoriajr.nfe.pr.ibaiti.GeradorTXT(leitorXMLIbaiti.lerXML(path));
                    geradorTXT.gerarTXT(destino, btnConsiderarISS.isSelected());
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } catch (IOException ex) {
                    Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                break;
            }
                
            case "Irecê - BA": {
                com.constanzooficial.integracao.controller.nfse.ba.irece.ControllerLeitor leitor = new com.constanzooficial.integracao.controller.nfse.ba.irece.ControllerLeitor();

                String cpfCnpjPrestador = null;
                switch (comboPrestador.getSelectedItem().toString()) {

                    case "ZN Odontologia (Matriz)":
                        cpfCnpjPrestador = "13200792000190";
                        break;
                    case "ZN Odontologia (Filial)":
                        cpfCnpjPrestador = "13200792000351";
                        break;
                }
                try {
                    geradorTxt = new GeradorTXT(leitor.lerNotas(selectedFiles, btnConsiderarISS.isSelected(), cpfCnpjPrestador));
                    geradorTxt.gerarTxt(selectedFiles[0].getParentFile().getPath(), radioEmitidas.isSelected() ? 0 : 1);
                } catch (IOException ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                } catch (Exception ex) {
                Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
            }
                break;
            }
                
            case "João Dourado - BA": {
                com.constanzooficial.integracao.controller.nfse.ba.joaoDourado.ControllerLeitor leitor = new com.constanzooficial.integracao.controller.nfse.ba.joaoDourado.ControllerLeitor();

                try {
                    geradorTxt = new GeradorTXT(leitor.lerNotas(selectedFiles, btnConsiderarISS.isSelected()));
                    geradorTxt.gerarTxt(selectedFiles[0].getParentFile().getPath(), radioEmitidas.isSelected() ? 0 : 1);
                } catch (IOException ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                } catch (Exception ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            }
            
            case "Mossoró - RN": {
                com.constanzooficial.integracao.controller.nfse.rn.mossoro.ControllerLeitor leitorMossoro = new com.constanzooficial.integracao.controller.nfse.rn.mossoro.ControllerLeitor();

                try {
                    geradorTxt = new GeradorTXT(leitorMossoro.lerNotas(path, btnConsiderarISS.isSelected()));
                    geradorTxt.gerarTxt(selectedFiles[0].getParentFile().getPath(), radioEmitidas.isSelected() ? 0 : 1);
                } catch (Exception ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                }
                break;
            }

            case "Nova Iguaçu - RJ":
                com.constanzooficial.integracao.controller.nfse.rj.novaIguacu.ControllerLeitor leitorNovaIguacu = new com.constanzooficial.integracao.controller.nfse.rj.novaIguacu.ControllerLeitor();

                try {
                    geradorTxt = new GeradorTXT(leitorNovaIguacu.lerNotas(path, btnConsiderarISS.isSelected()));
                    geradorTxt.gerarTxt(selectedFiles[0].getParent(), 0/*radioEmitidas.isSelected() ? 0 : 1*/);
                } catch (IOException ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                }
                break;

            case "Osasco - SP": {
                com.constanzooficial.integracao.controller.nfse.sp.osasco.ControllerLeitor leitor = new com.constanzooficial.integracao.controller.nfse.sp.osasco.ControllerLeitor();

                try {
                    geradorTxt = new GeradorTXT(leitor.lerNotas(path, btnConsiderarISS.isSelected()));
                    geradorTxt.gerarTxt(selectedFiles[0].getParent(), 0/*radioEmitidas.isSelected() ? 0 : 1*/);
                } catch (IOException ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                }
                break;
            }

            case "Rio Verde - GO": {
                com.constanzooficial.integracao.controller.nfse.go.rioVerde.ControllerLeitor leitor = new com.constanzooficial.integracao.controller.nfse.go.rioVerde.ControllerLeitor();

                try {
                    try {
                        geradorTxt = new GeradorTXT(leitor.lerNotas(selectedFiles, btnConsiderarISS.isSelected()));
                    } catch (Exception ex) {
                        Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    geradorTxt.gerarTxt(destino, radioEmitidas.isSelected() ? 0 : 1);

                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } catch (IOException ex) {
                    Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                break;
            }

            case "Salvador - BA":
                com.aldeiaconsultoriajr.nfe.ba.salvador.LeitorXML leitorXMLSalvador = new com.aldeiaconsultoriajr.nfe.ba.salvador.LeitorXML();
                try {
                    com.aldeiaconsultoriajr.nfe.ba.salvador.GeradorTXT geradorTXT = new com.aldeiaconsultoriajr.nfe.ba.salvador.GeradorTXT(leitorXMLSalvador.lerXML(path));
                    geradorTXT.gerarTXT(destino, (radioEmitidas.isSelected()) ? 1 : 2, btnConsiderarISS.isSelected());
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } catch (IOException ex) {
                    Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                break;

            case "São Raimundo Nonato - PI": {
                com.constanzooficial.integracao.controller.nfse.pi.saoRaimundoNonato.ControllerLeitor leitor = new com.constanzooficial.integracao.controller.nfse.pi.saoRaimundoNonato.ControllerLeitor();

                String cnpjPrestador = null;
                switch (comboPrestador.getSelectedItem().toString()) {

                    case "LB & Filhos":
                        cnpjPrestador = "07194240000113";
                        break;
                }
                try {
                    geradorTxt = new GeradorTXT(leitor.lerNotas(selectedFiles, btnConsiderarISS.isSelected(), cnpjPrestador));
                    geradorTxt.gerarTxt(destino, radioEmitidas.isSelected() ? 0 : 1);
                } catch (Exception ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                }
                break;
            }

            case "São Vicente - SP":
                com.constanzooficial.integracao.controller.nfse.sp.saoVicente.ControllerLeitor leitorSaoVicente = new com.constanzooficial.integracao.controller.nfse.sp.saoVicente.ControllerLeitor();

                try {
                    geradorTxt = new GeradorTXT(leitorSaoVicente.lerNotas(selectedFiles, radioEmitidas.isSelected() ? 0 : 1, btnConsiderarISS.isSelected()));
                    geradorTxt.gerarTxt(selectedFiles[0].getParentFile().getPath(), radioEmitidas.isSelected() ? 0 : 1);
                } catch (IOException ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                }
                break;

            case "Vila Velha - ES":
                com.aldeiaconsultoriajr.nfe.es.vilaVelha.LeitorXML leitorXMLVilaVelha = new com.aldeiaconsultoriajr.nfe.es.vilaVelha.LeitorXML();

                try {
                    com.aldeiaconsultoriajr.nfe.es.vilaVelha.GeradorTXT geradorTXT = new com.aldeiaconsultoriajr.nfe.es.vilaVelha.GeradorTXT(leitorXMLVilaVelha.lerXML(path));
                    geradorTXT.gerarTXT(destino, btnConsiderarISS.isSelected());
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } catch (IOException ex) {
                    Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                break;
                
            case "Vitória da Conquista - BA": {
                com.constanzooficial.integracao.controller.nfse.ba.vitoriaDaConquista.ControllerLeitor leitor = new com.constanzooficial.integracao.controller.nfse.ba.vitoriaDaConquista.ControllerLeitor();

                try {
                    geradorTxt = new GeradorTXT(leitor.lerNotas(selectedFiles, btnConsiderarISS.isSelected()));
                    geradorTxt.gerarTxt(selectedFiles[0].getParentFile().getPath(), radioEmitidas.isSelected() ? 0 : 1);
                } catch (IOException ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex, "Erro!", JOptionPane.ERROR_MESSAGE);
                } catch (Exception ex) {
                    Logger.getLogger(ViewNotaMunicipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            }
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        JOptionPane.showMessageDialog(null, "Conversão concluída com sucesso!");
    }//GEN-LAST:event_btnConverterArquivoActionPerformed

    private void comboMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMunicipioActionPerformed
        switch (comboMunicipio.getSelectedItem().toString()) {
            case "Município":
                campoCaminhoArquivo.setText("Selecione um município");
                btnSelecaoArquivo.setEnabled(false);
                comboPrestador.setEnabled(false);
                break;
            case "Agrolândia - SC":
            case "Canoas - RS":
                campoCaminhoArquivo.setText("Selecione o arquivo ZIP das notas");
                btnSelecaoArquivo.setEnabled(true);
                comboPrestador.setEnabled(false);
                break;
            case "Barueri - SP":
                campoCaminhoArquivo.setText("Selecione o arquivo ZIP ou os TXTs das notas");
                btnSelecaoArquivo.setEnabled(true);
                comboPrestador.setEnabled(true);
                break;
            case "Bento Gonçalves - RS":
                campoCaminhoArquivo.setText("Selecione o arquivo ZIP das notas");
                btnSelecaoArquivo.setEnabled(true);
                comboPrestador.setEnabled(false);
                break;
            case "Bauru - SP":
            case "Cubatão - SP":
                campoCaminhoArquivo.setText("Selecione o arquivo ZIP ou os XMLs das notas");
                btnSelecaoArquivo.setEnabled(true);
                comboPrestador.setEnabled(false);
                break;
            case "Goiânia - GO":
            case "São Raimundo Nonato - PI":
            case "Vitória da Conquista - BA":
                campoCaminhoArquivo.setText("Selecione o arquivo XML das notas");
                btnSelecaoArquivo.setEnabled(true);
                comboPrestador.setEnabled(true);
                btnConverterArquivo.setEnabled(true);
                break;
            case "Irecê - BA":
                campoCaminhoArquivo.setText("Selecione os arquivos XMLs das notas");
                btnSelecaoArquivo.setEnabled(true);
                comboPrestador.setEnabled(true);
                break;
            case "Brasília - DF":
            case "João Dourado - BA":
            case "São Vicente - SP":
                campoCaminhoArquivo.setText("Selecione os arquivos XMLs das notas");
                btnSelecaoArquivo.setEnabled(true);
                comboPrestador.setEnabled(false);
                break;
            default:
                campoCaminhoArquivo.setText("Selecione o arquivo XML das notas");
                btnSelecaoArquivo.setEnabled(true);
                comboPrestador.setEnabled(false);
                break;
        }
        btnGroupTipo.clearSelection();
        radioEmitidas.setEnabled(false);
        radioRecebidas.setEnabled(false);
        btnConsiderarISS.setEnabled(false);
        btnConverterArquivo.setEnabled(false);
    }//GEN-LAST:event_comboMunicipioActionPerformed

    private void btnSelecaoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecaoArquivoActionPerformed

        btnGroupTipo.clearSelection();
        radioEmitidas.setEnabled(false);
        radioRecebidas.setEnabled(false);
        btnConsiderarISS.setEnabled(false);
        btnConverterArquivo.setEnabled(false);

        JFileChooser fc = new JFileChooser(selectedFiles == null ? null : selectedFiles[0].getParentFile());

        switch (comboMunicipio.getSelectedItem().toString()) {
            case "Agrolândia - SC":
            case "Barueri - SP":
                fc.setFileFilter(new FileNameExtensionFilter("ZIP e/ou TXT", "zip", "txt"));
                fc.setMultiSelectionEnabled(true);
                break;
            case "Bento Gonçalves - RS":
            case "Canoas - RS":
                fc.setFileFilter(new FileNameExtensionFilter("ZIP", "zip"));
                //fc.setMultiSelectionEnabled(true);
                break;
            //case "Caicó - RN":
            case "Brasília - DF":
            case "Goiânia - GO":
            case "Irecê - BA":
            case "João Dourado - BA":
            case "Mossoró - RN":
            case "São Raimundo Nonato - PI":
            case "São Vicente - SP":
            case "Vitória da Conquista - BA":
                fc.setFileFilter(new FileNameExtensionFilter("XML", "xml"));
                fc.setMultiSelectionEnabled(true);
                break;
            case "Bauru - SP":
            case "Cubatão - SP":
                fc.setFileFilter(new FileNameExtensionFilter("ZIP e/ou XML", "zip", "xml"));
                fc.setMultiSelectionEnabled(true);
                break;
            default:
                fc.setFileFilter(new FileNameExtensionFilter("XML", "xml"));
                break;
        }

        fc.setAcceptAllFileFilterUsed(false);

        int opcao = fc.showOpenDialog(null);

        if (opcao == JFileChooser.APPROVE_OPTION) {

            selectedFiles = fc.getSelectedFiles();

            if (selectedFiles == null || selectedFiles.length == 0) {
                selectedFiles = new File[1];
                selectedFiles[0] = fc.getSelectedFile();
            }

            if (selectedFiles != null && selectedFiles.length > 1) {
                campoCaminhoArquivo.setText(selectedFiles[0].getParentFile().getPath() + "\\[" + selectedFiles.length + " arquivos].xml");
            } else {
                campoCaminhoArquivo.setText(selectedFiles[0].getPath());
            }

            switch (comboMunicipio.getSelectedItem().toString()) {
                case "Agrolândia - SC":
                case "Barueri - SP":
                case "Bauru - SP":
                case "Bento Gonçalves - RS":
                case "Brasília - DF":
                //case "Caicó - RN":
                case "Campo Novo do Parecis - MT":
                case "Canoas - RS":
                case "Colatina - ES":
                case "Cubatão - SP":
                case "Goiânia - GO":
                case "Ibaiti - PR":
                case "Irecê - BA":
                case "João Dourado - BA":
                case "Mossoró - RN":
                case "Nova Iguaçu - RJ":
                case "Osasco - SP":
                case "Rio Verde - GO":
                case "São Raimundo Nonato - PI":
                case "Vila Velha - ES":
                case "Vitória da Conquista - BA":
                    radioEmitidas.setEnabled(true);
                    radioRecebidas.setEnabled(false);
                    break;
                case "Salvador - BA":
                case "São Vicente - SP":
                    radioEmitidas.setEnabled(true);
                    radioRecebidas.setEnabled(true);
                    break;
                default:
                    radioEmitidas.setEnabled(false);
                    radioRecebidas.setEnabled(false);
                    break;
            }
            btnGroupTipo.clearSelection();
            btnConsiderarISS.setEnabled(true);
            btnConsiderarISS.setSelected(true);
        }
    }//GEN-LAST:event_btnSelecaoArquivoActionPerformed

    private void radioEmitidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEmitidasActionPerformed
        btnConverterArquivo.setEnabled(true);
    }//GEN-LAST:event_radioEmitidasActionPerformed

    private void radioRecebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRecebidasActionPerformed
        btnConverterArquivo.setEnabled(true);
    }//GEN-LAST:event_radioRecebidasActionPerformed

    private void btnConsiderarISSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsiderarISSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsiderarISSActionPerformed

    private void campoCaminhoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCaminhoArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCaminhoArquivoActionPerformed

    private void comboPrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPrestadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPrestadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.setLookAndFeel(new com.jgoodies.looks.plastic.Plastic3DLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewNotaMunicipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnConsiderarISS;
    private javax.swing.JButton btnConverterArquivo;
    private javax.swing.ButtonGroup btnGroupTipo;
    private javax.swing.JButton btnSelecaoArquivo;
    private javax.swing.JTextField campoCaminhoArquivo;
    private javax.swing.JComboBox<String> comboMunicipio;
    private javax.swing.JComboBox<String> comboPrestador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton radioEmitidas;
    private javax.swing.JRadioButton radioRecebidas;
    // End of variables declaration//GEN-END:variables
}
