package com.constanzooficial.integracao.view;

import com.constanzooficial.integracao.controller.ControllerClientes;
import com.constanzooficial.integracao.controller.ControllerConfig;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Yuri Fernandes de Oliveira
 */
public class ViewMenu extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenu
     */
    public ViewMenu() {
        initComponents();
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        this.setSize(Double.valueOf(d.getWidth()).intValue(), 100);
        this.setLocation(0, 0);
        
        try {
            Image iconePrograma = ImageIO.read(getClass().getResourceAsStream("/res/iconeNFSe.png"));
            this.setIconImage(iconePrograma);
        } catch (IOException ex) {
            Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        try {
            new ControllerConfig().loadConfigs();
            new ControllerClientes().carregarClientes();
        } catch (IOException ex) {
            Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        menuConversor = new javax.swing.JMenu();
        menuNfseMunicipais = new javax.swing.JMenuItem();
        menuEmpresasEspecificas = new javax.swing.JMenuItem();
        menuRetirarISS = new javax.swing.JMenuItem();
        menuWebServices = new javax.swing.JMenu();
        menuSaoPauloSP = new javax.swing.JMenu();
        menuSaoPauloSPBaixarNotas = new javax.swing.JMenuItem();
        menuSaoPauloSPEmitirGuias = new javax.swing.JMenuItem();
        menuSaoPauloSPListaClientes = new javax.swing.JMenuItem();
        menuConfiguracoes = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Integração Constanzo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menuConversor.setText("Conversor");

        menuNfseMunicipais.setText("NFSe municipais");
        menuNfseMunicipais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNfseMunicipaisActionPerformed(evt);
            }
        });
        menuConversor.add(menuNfseMunicipais);

        menuEmpresasEspecificas.setText("Empresas específicas");
        menuEmpresasEspecificas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpresasEspecificasActionPerformed(evt);
            }
        });
        menuConversor.add(menuEmpresasEspecificas);

        menuRetirarISS.setText("Retirar ISS");
        menuRetirarISS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRetirarISSActionPerformed(evt);
            }
        });
        menuConversor.add(menuRetirarISS);

        barraMenu.add(menuConversor);

        menuWebServices.setText("WebServices");

        menuSaoPauloSP.setText("São Paulo - SP");

        menuSaoPauloSPBaixarNotas.setText("Baixar notas");
        menuSaoPauloSPBaixarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaoPauloSPBaixarNotasActionPerformed(evt);
            }
        });
        menuSaoPauloSP.add(menuSaoPauloSPBaixarNotas);

        menuSaoPauloSPEmitirGuias.setText("Emitir guias");
        menuSaoPauloSPEmitirGuias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaoPauloSPEmitirGuiasActionPerformed(evt);
            }
        });
        menuSaoPauloSP.add(menuSaoPauloSPEmitirGuias);

        menuSaoPauloSPListaClientes.setText("Lista de Clientes");
        menuSaoPauloSPListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaoPauloSPListaClientesActionPerformed(evt);
            }
        });
        menuSaoPauloSP.add(menuSaoPauloSPListaClientes);

        menuWebServices.add(menuSaoPauloSP);

        menuConfiguracoes.setText("Configurações");
        menuConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConfiguracoesActionPerformed(evt);
            }
        });
        menuWebServices.add(menuConfiguracoes);

        barraMenu.add(menuWebServices);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        barraMenu.add(menuSair);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuNfseMunicipaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNfseMunicipaisActionPerformed
        new ViewNotaMunicipal().setVisible(true);
    }//GEN-LAST:event_menuNfseMunicipaisActionPerformed

    private void menuEmpresasEspecificasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpresasEspecificasActionPerformed
        new ViewEmpresaEspecifica().setVisible(true);
    }//GEN-LAST:event_menuEmpresasEspecificasActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConfiguracoesActionPerformed
        new ViewConfiguracoes().setVisible(true);
    }//GEN-LAST:event_menuConfiguracoesActionPerformed

    private void menuSaoPauloSPBaixarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaoPauloSPBaixarNotasActionPerformed
        new ViewWS().setVisible(true);
    }//GEN-LAST:event_menuSaoPauloSPBaixarNotasActionPerformed

    private void menuRetirarISSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRetirarISSActionPerformed
        new ViewRetirarIss().setVisible(true);
    }//GEN-LAST:event_menuRetirarISSActionPerformed

    private void menuSaoPauloSPListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaoPauloSPListaClientesActionPerformed
        new ViewClientes().setVisible(true);
    }//GEN-LAST:event_menuSaoPauloSPListaClientesActionPerformed

    private void menuSaoPauloSPEmitirGuiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaoPauloSPEmitirGuiasActionPerformed
        new ViewEmitirGuias().setVisible(true);
    }//GEN-LAST:event_menuSaoPauloSPEmitirGuiasActionPerformed
    
    private void habilitarMenu() {
        for (int i = 0; i < barraMenu.getMenuCount() - 1; i++) {
            barraMenu.getMenu(i).setEnabled(true);
        }
    }
    
    private void desabilitarMenu() {
        for (int i = 0; i < barraMenu.getMenuCount() - 1; i++) {
            barraMenu.getMenu(i).setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.setLookAndFeel(new com.jgoodies.looks.plastic.Plastic3DLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem menuConfiguracoes;
    private javax.swing.JMenu menuConversor;
    private javax.swing.JMenuItem menuEmpresasEspecificas;
    private javax.swing.JMenuItem menuNfseMunicipais;
    private javax.swing.JMenuItem menuRetirarISS;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuSaoPauloSP;
    private javax.swing.JMenuItem menuSaoPauloSPBaixarNotas;
    private javax.swing.JMenuItem menuSaoPauloSPEmitirGuias;
    private javax.swing.JMenuItem menuSaoPauloSPListaClientes;
    private javax.swing.JMenu menuWebServices;
    // End of variables declaration//GEN-END:variables
}
