package com.constanzooficial.integracao.view;

import com.constanzooficial.integracao.controller.ControllerClientes;
import com.constanzooficial.integracao.controller.ControllerWebService;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Yuri Fernandes de Oliveira
 */
public class ViewWS extends javax.swing.JFrame implements ViewComBarra {

    /**
     * Creates new form ViewWS
     */
    public ViewWS() {
        initComponents();

        this.setLocationRelativeTo(null);

        try {
            Image iconePrograma = ImageIO.read(getClass().getResourceAsStream("/res/iconeNFSe.png"));
            this.setIconImage(iconePrograma);

            BufferedImage iconeAbrirArquivo = ImageIO.read(getClass().getResourceAsStream("/res/iconeAbrirArquivo.png"));
            Image dimg = iconeAbrirArquivo.getScaledInstance(btnSelecionarPasta.getWidth() - 15, btnSelecionarPasta.getHeight() - 10, Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(dimg);
            btnSelecionarPasta.setIcon(imageIcon);
        } catch (IOException ex) {
            Logger.getLogger(ViewWS.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Preenche a comboBox do ano
        Date date = new Date();
        Calendar cal = new GregorianCalendar();
        cal.setTimeInMillis(date.getTime());
        int ano = cal.get(Calendar.YEAR);
        for (int i = 2010; i <= ano; i++) {
            comboAno.addItem(Integer.toString(i));
        }
        comboAno.setSelectedIndex(comboAno.getItemCount() - 1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboMes = new javax.swing.JComboBox<>();
        campoPasta = new javax.swing.JTextField();
        btnSelecionarPasta = new javax.swing.JButton();
        btnSelecionarClientes = new javax.swing.JButton();
        btnBaixarNotas = new javax.swing.JButton();
        comboAno = new javax.swing.JComboBox<>();
        barraProgresso = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Integração Constanzo - São Paulo WS");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        comboMes.setEnabled(false);
        comboMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMesActionPerformed(evt);
            }
        });

        campoPasta.setEditable(false);
        campoPasta.setText("Selecione uma pasta para salvar as notas");
        campoPasta.setFocusable(false);

        btnSelecionarPasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarPastaActionPerformed(evt);
            }
        });

        btnSelecionarClientes.setText("Selecionar clientes");
        btnSelecionarClientes.setEnabled(false);
        btnSelecionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarClientesActionPerformed(evt);
            }
        });

        btnBaixarNotas.setText("Baixar notas");
        btnBaixarNotas.setEnabled(false);
        btnBaixarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaixarNotasActionPerformed(evt);
            }
        });

        comboAno.setEnabled(false);

        barraProgresso.setForeground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoPasta, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnSelecionarPasta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboAno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSelecionarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnBaixarNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barraProgresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSelecionarPasta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPasta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSelecionarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(comboMes)
                    .addComponent(comboAno))
                .addGap(18, 18, 18)
                .addComponent(barraProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBaixarNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarClientesActionPerformed
        new ViewClientes(this).setVisible(true);
    }//GEN-LAST:event_btnSelecionarClientesActionPerformed

    private void btnSelecionarPastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarPastaActionPerformed

        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int opcao = fc.showOpenDialog(null);
        if (opcao == JFileChooser.APPROVE_OPTION) {
            campoPasta.setText(fc.getSelectedFile().getPath());
            comboMes.setEnabled(true);
            comboAno.setEnabled(true);
        }
    }//GEN-LAST:event_btnSelecionarPastaActionPerformed

    private void comboMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMesActionPerformed

        if (comboMes.getSelectedIndex() != 0) {
            btnSelecionarClientes.setEnabled(true);
            if (!ControllerClientes.getClientes().isEmpty()) {
                btnBaixarNotas.setEnabled(true);
            }
        } else {
            btnSelecionarClientes.setEnabled(false);
            btnBaixarNotas.setEnabled(false);
        }
    }//GEN-LAST:event_comboMesActionPerformed

    private void btnBaixarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaixarNotasActionPerformed

        // Define o valor máximo da progressBar
        barraProgresso.setMaximum(ControllerClientes.getClientes().size());
        barraProgresso.setValue(0);
        btnSelecionarPasta.setEnabled(false);
        comboMes.setEnabled(false);
        comboAno.setEnabled(false);
        btnSelecionarClientes.setEnabled(false);
        btnBaixarNotas.setEnabled(false);
        try {
            ControllerWebService webService = new ControllerWebService(this);

            Date date = new Date();
            Calendar cal = new GregorianCalendar();
            cal.setTimeInMillis(date.getTime());
            int ano = cal.get(Calendar.YEAR);

            webService.baixarNotas(new File(campoPasta.getText()), comboMes.getSelectedIndex(), Integer.valueOf((String) comboAno.getSelectedItem()), 8); // Último argumento é o número de threads

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(ViewWS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBaixarNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.setLookAndFeel(new com.jgoodies.looks.plastic.Plastic3DLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewWS().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgresso;
    private javax.swing.JButton btnBaixarNotas;
    private javax.swing.JButton btnSelecionarClientes;
    private javax.swing.JButton btnSelecionarPasta;
    private javax.swing.JTextField campoPasta;
    private javax.swing.JComboBox<String> comboAno;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnBaixarNotas() {
        return btnBaixarNotas;
    }

    @Override
    public synchronized void incrementarBarra() {
        barraProgresso.setValue(barraProgresso.getValue() + 1);
        if (barraProgresso.getValue() == barraProgresso.getMaximum()) {
            btnSelecionarPasta.setEnabled(true);
            comboMes.setEnabled(true);
            comboAno.setEnabled(true);
            btnSelecionarClientes.setEnabled(true);
            btnBaixarNotas.setEnabled(true);
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            JOptionPane.showMessageDialog(this, "Notas baixadas com sucesso!");
        }
    }
}
