package com.constanzooficial.integracao.view;

import com.constanzooficial.integracao.controller.ControllerConfig;
import com.constanzooficial.integracao.model.ModelConfig;
import com.constanzooficial.integracao.util.MyUtils;
import com.constanzooficial.integracao.util.UtilAES;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Yuri Fernandes de Oliveira
 */
public class ViewConfiguracoes extends javax.swing.JFrame {

    /**
     * Creates new form ViewConfiguracoes
     */
    public ViewConfiguracoes() {
        initComponents();

        try {
            BufferedImage iconeAbrirArquivo = ImageIO.read(getClass().getResourceAsStream("/res/iconeAbrirArquivo.png"));
            Image dimg = iconeAbrirArquivo.getScaledInstance(btnSelecaoArquivo.getWidth() - 15, btnSelecaoArquivo.getHeight() - 10, Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(dimg);
            btnSelecaoArquivo.setIcon(imageIcon);
        } catch (IOException ex) {
            Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }

        if (ModelConfig.getInstance().getPkcs12file() != null) {
            campoCaminhoArquivo.setText(ModelConfig.getInstance().getPkcs12file().getPath());
            campoAlias.setText(ModelConfig.getInstance().getPrivateKeyAlias());
            try {
                campoSenha.setText(UtilAES.getInstance().decrypt(ModelConfig.getInstance().getPassword()));
                System.out.println(UtilAES.getInstance().decrypt(ModelConfig.getInstance().getPassword()));
            } catch (Exception ex) {
                Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
            }
            campoCnpj.setText(ModelConfig.getInstance().getCnpj());
            campoInscricaoMunicipal.setText(ModelConfig.getInstance().getInscricaoMunicipal());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCertificadoDigital = new javax.swing.JPanel();
        campoCaminhoArquivo = new javax.swing.JTextField();
        labelCertificadoDigital = new javax.swing.JLabel();
        labelArquivo = new javax.swing.JLabel();
        btnSelecaoArquivo = new javax.swing.JButton();
        labelAlias = new javax.swing.JLabel();
        campoAlias = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        painelDadosEmpresa = new javax.swing.JPanel();
        labelDadosEmpresa = new javax.swing.JLabel();
        campoCnpj = new javax.swing.JFormattedTextField();
        labelCnpj = new javax.swing.JLabel();
        campoInscricaoMunicipal = new javax.swing.JFormattedTextField();
        labelInscricaoMunicipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Integração Constanzo - Configurações");

        painelCertificadoDigital.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        campoCaminhoArquivo.setEditable(false);
        campoCaminhoArquivo.setText("Selecione um arquivo");
        campoCaminhoArquivo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campoCaminhoArquivo.setFocusable(false);

        labelCertificadoDigital.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelCertificadoDigital.setText("Certificado digital");

        labelArquivo.setText("Arquivo:");

        btnSelecaoArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/iconeAbrirArquivo.png"))); // NOI18N
        btnSelecaoArquivo.setToolTipText("");
        btnSelecaoArquivo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSelecaoArquivo.setMaximumSize(new java.awt.Dimension(40, 30));
        btnSelecaoArquivo.setMinimumSize(new java.awt.Dimension(40, 30));
        btnSelecaoArquivo.setPreferredSize(new java.awt.Dimension(40, 30));
        btnSelecaoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecaoArquivoActionPerformed(evt);
            }
        });

        labelAlias.setText("Alias:");

        campoAlias.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelSenha.setText("Senha:");

        javax.swing.GroupLayout painelCertificadoDigitalLayout = new javax.swing.GroupLayout(painelCertificadoDigital);
        painelCertificadoDigital.setLayout(painelCertificadoDigitalLayout);
        painelCertificadoDigitalLayout.setHorizontalGroup(
            painelCertificadoDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCertificadoDigitalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCertificadoDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCertificadoDigital)
                    .addGroup(painelCertificadoDigitalLayout.createSequentialGroup()
                        .addGroup(painelCertificadoDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelAlias)
                            .addComponent(labelArquivo)
                            .addComponent(labelSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelCertificadoDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoSenha)
                            .addComponent(campoCaminhoArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(campoAlias))
                        .addGap(0, 0, 0)
                        .addComponent(btnSelecaoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCertificadoDigitalLayout.setVerticalGroup(
            painelCertificadoDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCertificadoDigitalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCertificadoDigital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCertificadoDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCertificadoDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoCaminhoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelArquivo))
                    .addComponent(btnSelecaoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCertificadoDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAlias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCertificadoDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSenha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnSalvar.setMinimumSize(new java.awt.Dimension(100, 30));
        btnSalvar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnCancelar.setMinimumSize(new java.awt.Dimension(100, 30));
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        painelDadosEmpresa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelDadosEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelDadosEmpresa.setText("Dados da empresa");

        try {
            campoCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCnpj.setToolTipText("");

        labelCnpj.setText("CNPJ:");

        campoInscricaoMunicipal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        labelInscricaoMunicipal.setText("Inscrição municipal:");

        javax.swing.GroupLayout painelDadosEmpresaLayout = new javax.swing.GroupLayout(painelDadosEmpresa);
        painelDadosEmpresa.setLayout(painelDadosEmpresaLayout);
        painelDadosEmpresaLayout.setHorizontalGroup(
            painelDadosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDadosEmpresa)
                    .addGroup(painelDadosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(painelDadosEmpresaLayout.createSequentialGroup()
                            .addComponent(labelCnpj)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelDadosEmpresaLayout.createSequentialGroup()
                            .addComponent(labelInscricaoMunicipal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoInscricaoMunicipal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        painelDadosEmpresaLayout.setVerticalGroup(
            painelDadosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDadosEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCnpj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoInscricaoMunicipal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInscricaoMunicipal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(painelCertificadoDigital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelDadosEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCertificadoDigital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDadosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecaoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecaoArquivoActionPerformed

        JFileChooser fc = new JFileChooser(".");
        fc.setFileFilter(new FileNameExtensionFilter("PKCS#12", "p12", "pfx"));
        fc.setAcceptAllFileFilterUsed(false);

        int opcao = fc.showOpenDialog(null);
        if (opcao == JFileChooser.APPROVE_OPTION) {
            campoCaminhoArquivo.setText(fc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btnSelecaoArquivoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (!campoCaminhoArquivo.getText().equals("Selecione um arquivo")
                && !campoAlias.getText().equals("")
                && campoSenha.getPassword().length > 0
                && campoCnpj.getText().charAt(0) != ' '
                && !campoInscricaoMunicipal.getText().equals("")) {

            ModelConfig config = ModelConfig.getInstance();
            config.setPkcs12file(new File(campoCaminhoArquivo.getText()));
            config.setPrivateKeyAlias(campoAlias.getText());
            try {
                config.setPassword(UtilAES.getInstance().encrypt(new String(campoSenha.getPassword())));
                config.setCnpj(MyUtils.trataCpfCnpj(campoCnpj.getText()));
                config.setInscricaoMunicipal(campoInscricaoMunicipal.getText());
                new ControllerConfig().saveConfigs();
            } catch (Exception ex) {
                Logger.getLogger(ViewConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.setLookAndFeel(new com.jgoodies.looks.plastic.Plastic3DLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            ViewConfiguracoes view = new ViewConfiguracoes();
            view.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSelecaoArquivo;
    private javax.swing.JTextField campoAlias;
    private javax.swing.JTextField campoCaminhoArquivo;
    private javax.swing.JFormattedTextField campoCnpj;
    private javax.swing.JFormattedTextField campoInscricaoMunicipal;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel labelAlias;
    private javax.swing.JLabel labelArquivo;
    private javax.swing.JLabel labelCertificadoDigital;
    private javax.swing.JLabel labelCnpj;
    private javax.swing.JLabel labelDadosEmpresa;
    private javax.swing.JLabel labelInscricaoMunicipal;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JPanel painelCertificadoDigital;
    private javax.swing.JPanel painelDadosEmpresa;
    // End of variables declaration//GEN-END:variables
}
